# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: predict.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'predict.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rpredict.proto\x12\x07predict\"\xa7\x01\n\x0ePredictRequest\x12\x17\n\x0f\x65xpenses_amount\x18\x01 \x01(\x02\x12\x11\n\ttotal_mts\x18\x02 \x01(\x02\x12\x13\n\x0b\x63overed_mts\x18\x03 \x01(\x02\x12\r\n\x05rooms\x18\x04 \x01(\x05\x12\x10\n\x08\x62\x65\x64rooms\x18\x05 \x01(\x05\x12\x11\n\tbathrooms\x18\x06 \x01(\x05\x12\x0f\n\x07garages\x18\x07 \x01(\x05\x12\x0f\n\x07\x61ntique\x18\x08 \x01(\x05\"=\n\x0fPredictResponse\x12\x12\n\nprediction\x18\x01 \x01(\x02\x12\x16\n\x0e\x65xecution_time\x18\x02 \x01(\x02\x32X\n\x16PropertyPricePredictor\x12>\n\x07Predict\x12\x17.predict.PredictRequest\x1a\x18.predict.PredictResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'predict_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_PREDICTREQUEST']._serialized_start=27
  _globals['_PREDICTREQUEST']._serialized_end=194
  _globals['_PREDICTRESPONSE']._serialized_start=196
  _globals['_PREDICTRESPONSE']._serialized_end=257
  _globals['_PROPERTYPRICEPREDICTOR']._serialized_start=259
  _globals['_PROPERTYPRICEPREDICTOR']._serialized_end=347
# @@protoc_insertion_point(module_scope)
